### ISSUE TITLE
Image of field doesn't transfer to Coach Tablet

### ISSUE THREAD

**Issue by Carter-Troha** [sjcbulldog/xeroscout#24]
The rest of the data transfers but the image of the field and bar don't. Also there is no way to create an image on the tablet.

**Comment by sjcbulldog** [comment]
The images are not designed to transfer.  Just make sure the images you need are on the coaches tablet.  The Create menu has a Create Image menu items that works for creating the image.

**Comment by Carter-Troha** [comment]
Just had to update the tablet
