### ISSUE TITLE
OPR calculation assumes matrix invertability

### ISSUE THREAD

**Issue by 1425** [sjcbulldog/xeroscout#27]
In OPRCalculator.cpp line 141 it is assumed that the matrix is invertible.  However, this is likely to not be the case.  

If it is not invertible, the program will likely end up with a bunch of nan values.

I believe that replacing the line with something like:

MatrixXd mpinv=mp.completeOrthogonalDecomposition().pseudoInverse();

Should solve the problem.  

I believe that line 137 of DPRCalculator.cpp has the same issue which can be solved in the same way.

**Comment by sjcbulldog** [comment]
Thanks for the suggestion.  Changes made  per your comments.
In version 0.6.8
