### ISSUE TITLE
Inability to elaborate on defence

### ISSUE THREAD

**Issue by AarushPalve** [sjcbulldog/xeroscout#33]
Right now it only shows if a robot played defense, it would be nice if the scouter could elaborate for further information.

**Comment by sjcbulldog** [comment]
There is a "text" type field you can add.  For instance, in the "General" tab there is a field that is for "Additional Notes".  Is this what you are looking for?  If so, you can add it to your forms.  Talk to Suhaani about how to do this, but you just change the JSON for the form to add the additional field and then create a new event.

**Comment by AarushPalve** [comment]
Hey Butch,
I was hoping for a text box for defense-specific notes.
-Aarush

**Comment by sjcbulldog** [comment]
Text boxes can be added by changing the JSON for the scouting form.  This is something that the scouting lead can do.  Please work with Suhaani to understand the scouting forms and how you add things to the forms.  If there is something that you are trying to do that cannot be done via updates of the forms, let me know via more comments here.

**Comment by suhaaniii** [comment]
Hi Aarush,
Yes, adding textboxes is something the scouting lead itself can do. I can teach you this when you are back from your trip.
